### ISSUE TITLE
Getting timeout errors without setting a timeout

### ISSUE THREAD

**Issue by scottpchow23** [plaid/plaid-ruby#370]
Hi there! We're using version 14.1.0 of the `plaid-ruby` gem and we're noticing that we're getting the following timeout error when the plaid request takes ~85 seconds:

```
Net::ReadTimeout: Net::ReadTimeout
  from net/protocol.rb:217:in `rbuf_fill'
  from net/protocol.rb:191:in `readuntil'
  from net/protocol.rb:201:in `readline'
  from net/http/response.rb:42:in `read_status_line'
  from net/http/response.rb:31:in `read_new'
  from net/http.rb:1528:in `block in transport_request'
  from net/http.rb:1519:in `catch'
  from net/http.rb:1519:in `transport_request'
  from net/http.rb:1492:in `request'
  from new_relic/agent/instrumentation/net.rb:52:in `block (2 levels) in request_with_newrelic_trace'
  from new_relic/agent/tracer.rb:371:in `capture_segment_error'
  from new_relic/agent/instrumentation/net.rb:51:in `block in request_with_newrelic_trace'
  from new_relic/agent.rb:507:in `disable_all_tracing'
  from new_relic/agent/instrumentation/net.rb:50:in `request_with_newrelic_trace'
  from faraday/adapter/net_http.rb:152:in `block in request_via_request_method'
  from net/http.rb:933:in `start'
  from faraday/adapter/net_http.rb:146:in `request_via_request_method'
  from faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'
  from faraday/adapter/net_http.rb:122:in `perform_request'
  from faraday/adapter/net_http.rb:66:in `block in call'
  from faraday/adapter.rb:50:in `connection'
  from faraday/adapter/net_http.rb:64:in `call'
  from faraday/rack_builder.rb:154:in `build_response'
  from faraday/connection.rb:511:in `run_request'
  from faraday/connection.rb:281:in `post'
  from plaid/api_client.rb:59:in `public_send'
  from plaid/api_client.rb:59:in `call_api'
  from plaid/api/plaid_api.rb:1965:in `identity_get_with_http_info'
  from plaid/api/plaid_api.rb:1913:in `identity_get'
```

Do we need to explicitly configure the timeout when initializing `Plaid::PlaidApi.new(...)`? When I looked over the generated code, I took [this comment](https://github.com/plaid/plaid-ruby/blob/3b8a4ee2d27b35de4c7c4a7ba3dedf94649e73d9/lib/plaid/configuration.rb#L92) to mean that we wouldn't need to configure it if we didn't want a timeout:

```ruby
    # The time limit for HTTP request in seconds.
    # Default to 0 (never times out).
    attr_accessor :timeout
```

This is how we are currently configuring our api client:
```ruby
    def self.client
      use_dev = ::Settings.get('use_dev')
      configuration = Plaid::Configuration.new
      configuration.api_key['PLAID-CLIENT-ID'] = ::Config.dig!('plaid', 'client_id')
      configuration.api_key['PLAID-SECRET'] = if use_dev
                                                ::Config.dig!('plaid', 'secret_dev')
                                              else
                                                ::Config.dig!('plaid', 'secret')
                                              end
      configuration.api_key['Plaid-Version'] = '2020-09-14'
      configuration.server_index = if use_dev
                                     Plaid::Configuration::Environment['development']
                                   else
                                     Plaid::Configuration::Environment[::Config.dig!('plaid', 'env')]
                                   end
      api_client = Plaid::ApiClient.new(
        configuration,
      )

      Plaid::PlaidApi.new(api_client)
    end
```

**Comment by kirubasagar** [comment]
Hi, I am facing this error too. Did you solve it by any chance?

**Comment by phoenixy1** [comment]
This is fixed in the current version of the ruby client library, which now states that the default timeout is 60 seconds.
